import turtle
def draw_square():
    window=turtle.Screen()#this is a public class used to draw shapes
    window.bgcolor("red")
    
    brad=turtle.Turtle()
    #Subclass of RawTurtle, has the same interface but draws on a default
    #Screen object created automatically when needed for the first time.
    brad.shape("turtle")
    brad.color("green")
    brad.speed(1)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)#just copy pasta
    brad.shape("arrow")
    brad.color("yellow")
    brad.speed(1)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    #changes to another shape
    brad.shape("circle")
    brad.color("yellow")
    brad.speed(1)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    #
    brad.shape("triangle")
    brad.color("yellow")
    brad.speed(2)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    window.exitonclick()
    brad.shape("turtle")
    brad.color("green")
    brad.speed(2)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)#just copy pasta
    brad.shape("arrow")
    brad.color("yellow")
    brad.speed(1)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    #changes to another shape
    brad.shape("circle")
    brad.color("yellow")
    brad.speed(2)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    #
    brad.shape("triangle")
    brad.color("yellow")
    brad.speed(2)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    window.exitonclick()
draw_square()
